name: build

on:
  push:

jobs:
  document:
    name: document
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v15
      - run: nix build
      - uses: actions/upload-artifact@v3
        with:
          name: docs
          path: result/docs
