name: CI

on:
  push:

jobs:
  # treefmt:
  #   name: treefmt
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: cachix/install-nix-action@v15
  #     - uses: cachix/cachix-action@v10
  #       with:
  #        name: sno2wman
  #        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
  #     - run: nix-shell --run "treefmt --fail-on-change"

  document:
    name: document
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v15
      - uses: cachix/cachix-action@v10
        with:
         name: sno2wman
         authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build
      - uses: actions/upload-artifact@v3
        with:
          name: docs
          path: result/docs

  gh-pages:
    name: gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        id: dl
        with:
          name: docs
          path: public
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ steps.dl.outputs.download-path }}
